# Generated by Django 5.1.5 on 2025-01-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_list',
        ),
    ]
