# Generated by Django 5.1.5 on 2025-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
