# Generated by Django 5.1.5 on 2025-01-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField(null=True)),
                ('birth', models.DateField(null=True)),
            ],
        ),
    ]
