# Generated by Django 5.1.5 on 2025-02-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song_keyword',
            table='keywords_song_keyword',
        ),
    ]
