# Generated by Django 5.1.5 on 2025-02-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='keyword',
        ),
    ]
