# Generated by Django 5.1.5 on 2025-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(default='', null=True, unique=True),
        ),
    ]
