# Generated by Django 5.1.5 on 2025-02-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_rename_name_keyword_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('emotion', 'Emotion'), ('weather', 'Weather'), ('situation', 'Situation'), ('genre', 'Genre')], default='emotion', max_length=10),
        ),
    ]
